services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"


  server:
    build: ./contact-us-server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db

  client:
    build: ./contact-us-page
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: http://server:3001